"""optional_blocked

Revision ID: b33f68adc216
Revises: 3c07471f4cc4
Create Date: 2024-09-26 17:09:37.993912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33f68adc216'
down_revision = '3c07471f4cc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocked_refresh_tokens', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('blocked_refresh_tokens', 'refresh_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocked_refresh_tokens', 'refresh_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('blocked_refresh_tokens', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
